import React, { useState, useEffect } from 'react';
import { Box, Typography, Button, Paper, Alert, AlertTitle } from '@mui/material';
import { useLocation } from 'react-router-dom';
import { Download, Email, Warning, CheckCircle } from '@mui/icons-material';
import InfoIcon from '@mui/icons-material/Info';
import { RegulatoryProfile } from '../types/regulatory';

const ProfileDashboard: React.FC = () => {
  //const [error, setError] = useState('');
  //const [activeProfile, setActiveProfile] = useState<RegulatoryProfile | null>(null);

  // const getComplianceColor = (status: string) => {
  //   switch (status) {
  //     case 'Compliant': return 'success';
  //     case 'Conditional': return 'warning';
  //     case 'Non-Compliant': return 'error';
  //     case 'Undetermined': return 'info';
  //     default: return 'default';
  //   }
  // };

  const downloadMarkdownReport = () => {
    if (!activeProfile) return;

    // Generate markdown content from the evaluation data
    const mdrJustification = activeProfile.classification.mdrJustification 
      ? activeProfile.classification.mdrJustification.map((justification: string) => `- ${justification}`).join('\n') 
      : 'N/A';

    const markdownContent = `# Regulatory Evaluation Report - ${activeProfile.deviceName}

## Device Information

- **Device Name:** ${activeProfile.deviceName}
- **Device Description:** ${activeProfile.deviceDescription}
- **Intended Purpose:** ${activeProfile.intendedPurpose}
- **Evaluation Date:** ${new Date(activeProfile.createdAt).toLocaleDateString()}

## MDR Classification

- **MDR Applicable:** ${activeProfile.classification.mdrApplicable ? 'Yes' : 'No'}
- **MDR Class:** ${activeProfile.classification.mdrApplicable ? activeProfile.classification.mdrClass : 'N/A'}
- **Applied Rules:** ${activeProfile.classification.mdrApplicable && activeProfile.classification.mdrRules ? activeProfile.classification.mdrRules.join(', ') : 'N/A'}

### Justification
${mdrJustification}

## AI Act Classification

- **AI Act Applicable:** ${activeProfile.classification.aiActApplicable ? 'Yes' : 'No'}
- **High Risk:** ${activeProfile.classification.aiActApplicable ? (activeProfile.classification.aiActHighRisk ? 'Yes' : 'No') : 'N/A'}
- **Annex Reference:** ${activeProfile.classification.aiActApplicable ? activeProfile.classification.aiActAnnexReference : 'N/A'}

### Justification
${activeProfile.classification.aiActJustification || 'N/A'}

## GDPR Requirements

- **GDPR Applicable:** ${activeProfile.classification.gdprApplicable ? 'Yes' : 'No'}
- **DPIA Required:** ${activeProfile.classification.gdprApplicable ? (activeProfile.classification.gdprRequiresDPIA ? 'Yes' : 'No') : 'N/A'}
- **Legal Bases:** ${activeProfile.classification.gdprApplicable && activeProfile.classification.gdprLegalBases ? activeProfile.classification.gdprLegalBases.join(', ') : 'N/A'}

### Justification
${activeProfile.classification.gdprJustification || 'N/A'}

## LLM Assessment

${activeProfile.llmAssessment || 'No assessment available.'}

## Minimalistic Documentation for CE Certification

This section provides guidance on the documentation required for your device's CE certification process.

- Documentation will be generated based on your final assessment and additional information
- Ensure all technical documentation is complete and compliant with applicable regulations
- Maintain detailed records of all testing and validation procedures
- Prepare risk management files and clinical evaluation reports as required

## Relevant TEF Services

Based on your device classification, the following services may be relevant:

- Regulatory strategy consulting
- Technical documentation preparation
- Clinical evaluation support
- Risk management assistance
- Quality management system implementation

## Important Notes

- This classification is based on the information provided and requires human review by qualified regulatory professionals before official submission
- Consult with notified bodies for official classification
- Prepare for regulatory audits and inspections

---

*This report was generated by the TEF Regulatory Compliance System on ${new Date().toISOString()}*
`;

    // Create a blob and trigger download
    const blob = new Blob([markdownContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${activeProfile.deviceName.replace(/\s+/g, '_')}_Regulatory_Evaluation_Report.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  const sendEmailReport = () => {
    if (!activeProfile) return;

    // Generate HTML content for email
    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .header { background-color: #2c3e50; color: white; padding: 20px; text-align: center; }
        .content { padding: 20px; }
        .section { margin-bottom: 20px; border-bottom: 1px solid #eee; padding-bottom: 10px; }
        .section-title { color: #2c3e50; font-size: 18px; }
        .device-info { background-color: #f8f9fa; padding: 15px; border-radius: 5px; margin-bottom: 20px; }
        .footer { margin-top: 30px; font-size: 12px; color: #777; }
    </style>
</head>
<body>
    <div class="header">
        <h1>TEF Regulatory Evaluation Report</h1>
        <p>Device: ${activeProfile.deviceName}</p>
    </div>
    
    <div class="content">
        <div class="device-info">
            <h2>Device Information</h2>
            <p><strong>Device Name:</strong> ${activeProfile.deviceName}</p>
            <p><strong>Description:</strong> ${activeProfile.deviceDescription}</p>
            <p><strong>Intended Purpose:</strong> ${activeProfile.intendedPurpose}</p>
            <p><strong>Evaluation Date:</strong> ${new Date(activeProfile.createdAt).toLocaleDateString()}</p>
        </div>

        <div class="section">
            <h2 class="section-title">MDR Classification</h2>
            <p><strong>MDR Applicable:</strong> ${activeProfile.classification.mdrApplicable ? 'Yes' : 'No'}</p>
            <p><strong>MDR Class:</strong> ${activeProfile.classification.mdrApplicable ? activeProfile.classification.mdrClass : 'N/A'}</p>
            <p><strong>Applied Rules:</strong> ${activeProfile.classification.mdrApplicable && activeProfile.classification.mdrRules ? activeProfile.classification.mdrRules.join(', ') : 'N/A'}</p>
        </div>

        <div class="section">
            <h2 class="section-title">AI Act Classification</h2>
            <p><strong>AI Act Applicable:</strong> ${activeProfile.classification.aiActApplicable ? 'Yes' : 'No'}</p>
            <p><strong>High Risk:</strong> ${activeProfile.classification.aiActApplicable ? (activeProfile.classification.aiActHighRisk ? 'Yes' : 'No') : 'N/A'}</p>
        </div>

        <div class="section">
            <h2 class="section-title">GDPR Requirements</h2>
            <p><strong>GDPR Applicable:</strong> ${activeProfile.classification.gdprApplicable ? 'Yes' : 'No'}</p>
            <p><strong>DPIA Required:</strong> ${activeProfile.classification.gdprApplicable ? (activeProfile.classification.gdprRequiresDPIA ? 'Yes' : 'No') : 'N/A'}</p>
        </div>

        <div class="section">
            <h2 class="section-title">LLM Assessment</h2>
            <p>${activeProfile.llmAssessment || 'No assessment available.'}</p>
        </div>

        <div class="footer">
            <p>This report was generated by the TEF Regulatory Compliance System on ${new Date().toISOString()}</p>
            <p><strong>Important Notice:</strong> This classification is based on the information provided and requires human review by qualified regulatory professionals before official submission.</p>
        </div>
    </div>
</body>
</html>
`;

    // Open email client with the HTML content
    const subject = encodeURIComponent(`Regulatory Evaluation Report - ${activeProfile.deviceName}`);
    const body = encodeURIComponent(htmlContent);
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  }

  const [error, setError] = useState('');
  const [activeProfile, setActiveProfile] = useState<RegulatoryProfile | null>(null);
  const location = useLocation();

  useEffect(() => {
    const loadEvaluation = () => {
      try {
        setError('');

        console.log('[ProfileDashboard] ==========  LOADING EVALUATION ==========');
        console.log('[ProfileDashboard] location:', location);
        console.log('[ProfileDashboard] location.state:', location.state);
        console.log('[ProfileDashboard] location.state type:', typeof location.state);
        console.log('[ProfileDashboard] location.state keys:', location.state ? Object.keys(location.state) : 'null');

        // Try to get evaluation from navigation state first
        const navigationState = location.state as any;
        console.log('[ProfileDashboard] navigationState:', navigationState);
        console.log('[ProfileDashboard] navigationState?.evaluation:', navigationState?.evaluation);

        if (navigationState?.evaluation) {
          console.log('[ProfileDashboard] ✅✅✅ Found evaluation in navigation state!');
          console.log('[ProfileDashboard] Evaluation object:', JSON.stringify(navigationState.evaluation, null, 2));
          setActiveProfile(navigationState.evaluation);
          console.log('[ProfileDashboard] setActiveProfile called with navigation data');
          return;
        }

        // Otherwise try sessionStorage
        console.log('[ProfileDashboard] No navigation state, checking sessionStorage...');
        const storedEvaluation = sessionStorage.getItem('latestEvaluation');
        console.log('[ProfileDashboard] sessionStorage has data:', !!storedEvaluation);

        if (storedEvaluation) {
          console.log('[ProfileDashboard] SessionStorage data length:', storedEvaluation.length);
          const evaluation = JSON.parse(storedEvaluation) as RegulatoryProfile;
          console.log('[ProfileDashboard] ✅✅✅ Found evaluation in sessionStorage!');
          console.log('[ProfileDashboard] Parsed evaluation:', JSON.stringify(evaluation, null, 2));
          setActiveProfile(evaluation);
          console.log('[ProfileDashboard] setActiveProfile called with sessionStorage data');
          return;
        }

        // No evaluation available
        console.log('[ProfileDashboard] ❌❌❌ NO EVALUATION FOUND ANYWHERE');
        setActiveProfile(null);

      } catch (err) {
        setError('Failed to load evaluation summary');
        console.error('[ProfileDashboard] ❌ Error loading evaluation:', err);
        setActiveProfile(null);
      }
    };

    loadEvaluation();
  }, [location]);





  return (
    <Box sx={{ py: 4 }}>
      <Typography variant="h4" component="h1" gutterBottom sx={{ fontWeight: 600, mb: 3 }}>
        Latest evaluation summary
      </Typography>

      <Typography variant="body1" paragraph sx={{ mb: 4, maxWidth: '800px' }}>
        View your latest regulatory evaluation summary. This data is temporary and will be cleared when you log out or close your session.
      </Typography>

      <Alert severity="info" icon={<InfoIcon />} sx={{ mb: 3 }}>
        <AlertTitle>Temporary Data</AlertTitle>
        This evaluation summary is stored temporarily in your browser session and will be automatically cleared when you log out or close your session for GDPR compliance.
      </Alert>

      {error && (
        <Alert severity="error" sx={{ mb: 3 }}>
          {error}
        </Alert>
      )}



      {activeProfile ? (
        <Paper elevation={2} sx={{ p: 3, mb: 3 }}>
          <Typography variant="h6" gutterBottom>
            Latest Evaluation Summary
          </Typography>
          <Typography variant="body2" color="text.secondary" paragraph>
            This evaluation summary incorporates your device information and provides a comprehensive regulatory classification.
          </Typography>
          
          <Box sx={{ display: 'flex', gap: 3, mb: 3 }}>
            <Button
              variant="outlined"
              startIcon={<Download />}
              onClick={() => downloadMarkdownReport()}
              disabled={!activeProfile}
            >
              Export & download report
            </Button>
            <Button
              variant="outlined"
              startIcon={<Email />}
              onClick={sendEmailReport}
              disabled={!activeProfile}
            >
              Send report by email
            </Button>
          </Box>

          {/* MDR Classification Section - Beautified */}
          <Paper elevation={2} sx={{ p: 3, mb: 3, backgroundColor: 'background.paper' }}>
            <Typography variant="h6" gutterBottom sx={{ color: 'primary.main' }}>
              MDR Classification
            </Typography>
            
            <Box sx={{ display: 'flex', alignItems: 'center', mb: 2 }}>
              <CheckCircle color="primary" sx={{ mr: 1 }} />
              <Typography variant="h6">
                MDR Classification: {activeProfile.classification.mdrApplicable ? `Class ${activeProfile.classification.mdrClass}` : 'Not Applicable'}
              </Typography>
            </Box>
            
            {activeProfile.classification.mdrApplicable && activeProfile.classification.mdrRules && activeProfile.classification.mdrRules.length > 0 && (
              <Box sx={{ mb: 2 }}>
                <Typography variant="subtitle2" color="text.secondary" sx={{ mb: 1 }}>
                  Applied Rules:
                </Typography>
                <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1 }}>
                  {activeProfile.classification.mdrRules.map((rule: string, index: number) => (
                    <Typography key={index} variant="caption" sx={{ 
                      backgroundColor: 'primary.light', 
                      px: 1, 
                      py: 0.5, 
                      borderRadius: 1 
                    }}>
                      {rule}
                    </Typography>
                  ))}
                </Box>
              </Box>
            )}
            
            <Typography variant="body2" paragraph>
              <strong>Applicability:</strong> {activeProfile.classification.mdrApplicable ? 'MDR applies to this device' : 'MDR does not apply to this device'}
            </Typography>
            
            {activeProfile.classification.mdrJustification && activeProfile.classification.mdrJustification.length > 0 && (
              <Box sx={{ mt: 2 }}>
                <Typography variant="subtitle1" gutterBottom>
                  <strong>Justification:</strong>
                </Typography>
                <Box sx={{ pl: 2 }}>
                  {activeProfile.classification.mdrJustification.map((justification: string, index: number) => (
                    <Typography key={index} variant="body2" paragraph sx={{ ml: 1 }}>
                      • {justification}
                    </Typography>
                  ))}
                </Box>
              </Box>
            )}
          </Paper>
          
          {/* AI Act Classification Section - Beautified */}
          <Paper elevation={2} sx={{ p: 3, mb: 3, backgroundColor: 'background.paper' }}>
            <Typography variant="h6" gutterBottom sx={{ color: 'secondary.main' }}>
              AI Act Classification
            </Typography>
            
            <Typography variant="body2" paragraph>
              <strong>Classification:</strong> {activeProfile.classification.aiActApplicable ? (activeProfile.classification.aiActHighRisk ? 'High-Risk' : 'Not High-Risk') : 'Not Applicable'}
            </Typography>
            
            <Typography variant="body2" paragraph>
              <strong>High Risk:</strong> {activeProfile.classification.aiActApplicable ? (activeProfile.classification.aiActHighRisk ? 'Yes' : 'No') : 'N/A'}
            </Typography>
            
            {activeProfile.classification.aiActJustification && (
              <Typography variant="body2" paragraph>
                <strong>Justification:</strong> {activeProfile.classification.aiActJustification}
              </Typography>
            )}
          </Paper>
          
          {/* GDPR Requirements Section - Beautified */}
          <Paper elevation={2} sx={{ p: 3, mb: 3, backgroundColor: 'background.paper' }}>
            <Typography variant="h6" gutterBottom sx={{ color: 'error.main' }}>
              GDPR Requirements
            </Typography>
            
            <Typography variant="body2" paragraph>
              <strong>Requirements:</strong> {activeProfile.classification.gdprApplicable ? (activeProfile.classification.gdprRequiresDPIA ? 'DPIA Required' : 'Standard Compliance') : 'Not Applicable'}
            </Typography>
            
            <Typography variant="body2" paragraph>
              <strong>DPIA Required:</strong> {activeProfile.classification.gdprApplicable ? (activeProfile.classification.gdprRequiresDPIA ? 'Yes' : 'No') : 'N/A'}
            </Typography>
            
            {activeProfile.classification.gdprJustification && (
              <Typography variant="body2" paragraph>
                <strong>Justification:</strong> {activeProfile.classification.gdprJustification}
              </Typography>
            )}
          </Paper>

          {/* Minimalistic Documentation Section - Moved from Provisional Assessment */}
          <Paper elevation={2} sx={{ p: 3, mb: 3, backgroundColor: 'background.paper' }}>
            <Typography variant="h6" gutterBottom sx={{ color: 'success.main' }}>
              Minimalistic Documentation for the CE Certification Process
            </Typography>
            
            <Typography variant="body2" paragraph>
              This section provides guidance on the documentation required for your device's CE certification process.
            </Typography>
            
            <Typography variant="body2" paragraph>
              <strong>Status:</strong> Documentation will be generated based on your final assessment and additional information.
            </Typography>
            
            <Alert severity="info" icon={<InfoIcon />} sx={{ mt: 2 }}>
              <AlertTitle>Documentation Tips</AlertTitle>
              Ensure all technical documentation is complete and compliant with applicable regulations.
              Maintain detailed records of all testing and validation procedures.
              Prepare risk management files and clinical evaluation reports as required.
            </Alert>
          </Paper>
          
          {/* Relevant TEF Services Section - Moved from Provisional Assessment */}
          <Paper elevation={2} sx={{ p: 3, mb: 3, backgroundColor: 'background.paper' }}>
            <Typography variant="h6" gutterBottom sx={{ color: 'info.main' }}>
              Relevant TEF Services
            </Typography>
            
            <Typography variant="body2" paragraph>
              Based on your device classification, the following services may be relevant for your regulatory compliance:
            </Typography>
            
            <Box sx={{ pl: 2, mt: 2 }}>
              <Typography variant="body2" paragraph sx={{ ml: 1 }}>
                • Regulatory strategy consulting
              </Typography>
              <Typography variant="body2" paragraph sx={{ ml: 1 }}>
                • Technical documentation preparation
              </Typography>
              <Typography variant="body2" paragraph sx={{ ml: 1 }}>
                • Clinical evaluation support
              </Typography>
              <Typography variant="body2" paragraph sx={{ ml: 1 }}>
                • Risk management assistance
              </Typography>
              <Typography variant="body2" paragraph sx={{ ml: 1 }}>
                • Quality management system implementation
              </Typography>
            </Box>
            
            <Alert severity="info" icon={<InfoIcon />} sx={{ mt: 2 }}>
              <AlertTitle>Service Recommendation</AlertTitle>
              Consult with our regulatory experts to determine the most appropriate services for your specific device and market requirements.
            </Alert>
          </Paper>
          
          {/* LLM Assessment Section - Moved from Provisional Assessment */}
          {activeProfile.llmAssessment && (
            <Paper elevation={2} sx={{ p: 3, mb: 3, backgroundColor: 'background.paper', border: '1px solid', borderColor: 'divider' }}>
              <Typography variant="h6" gutterBottom sx={{ color: 'info.main', mb: 2 }}>
                Comprehensive LLM Assessment
              </Typography>
              
              <Typography variant="body2" paragraph sx={{ whiteSpace: 'pre-line', fontSize: '0.875rem', lineHeight: 1.6 }}>
                {activeProfile.llmAssessment}
              </Typography>
              
              <Alert severity="info" icon={<InfoIcon />} sx={{ mt: 2 }}>
                <AlertTitle>Assessment Notes</AlertTitle>
                This LLM assessment provides a detailed regulatory analysis based on your device information.
                Use this as guidance for your compliance strategy, but always consult with qualified professionals for final determinations.
              </Alert>
            </Paper>
          )}

          <Alert severity="warning" icon={<Warning />} sx={{ mb: 2 }}>
            <AlertTitle>Important Notice</AlertTitle>
            This classification is based on the information provided and requires human review
            by qualified regulatory professionals before official submission.
          </Alert>

          <Alert severity="info" icon={<InfoIcon />}>
            <AlertTitle>Next Steps</AlertTitle>
            1. Review and complete your regulatory documentation
            2. Consult with notified bodies for official classification
            3. Submit for internal review and approval
            4. Prepare for regulatory audits and inspections
          </Alert>
        </Paper>
      ) : (
        <Alert severity="info" icon={<InfoIcon />} sx={{ mb: 3 }}>
          <AlertTitle>No Evaluation Available</AlertTitle>
          No evaluation has been completed yet. Please complete a regulatory scoping evaluation to generate your latest evaluation summary.
        </Alert>
      )}

      {/* <Box sx={{ display: 'flex', justifyContent: 'flex-end', mt: 3 }}>
      </Box>

      <Alert severity="info" icon={<InfoIcon />} sx={{ mt: 3 }}>
        <AlertTitle>Profile Management Tips</AlertTitle>
        Create separate profiles for different devices or major versions.
        Use the documentation center to maintain all required regulatory files.
        Regularly review and update profiles as regulations evolve.
      </Alert> */}
    </Box>
  );
}

export default ProfileDashboard;